name: Build and deploy Node.js project to Azure Function App - func-coursemosdown
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Functions 프로젝트 루트
  NODE_VERSION: '22.x'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies & build
        run: |
          npm install
          npm run build --if-present
          npm run test  --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZUREAPPSERVICE_CLIENTID_67294AC8315449FAAAC5A6E158163C5A }}
          tenant-id:     ${{ secrets.AZUREAPPSERVICE_TENANTID_20E80C5F03354CE68539DAC83FEC28CE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_262E945D174C4E44934ADBC70171688C }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name:  'func-coursemosdown'
          slot-name: 'Production'
          package:   ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
